name: create env file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create env file
      run: |
        touch .env
        echo "ENGINE_API_KEY=${{ secrets.API_TOKEN }}" >> .env
