name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set API Token
      run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
