name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Instalar dependências
      run: npm install
      
    - name: Baixar jQuery
      run: |
        mkdir -p assets
        wget -O assets/jquery.min.js https://code.jquery.com/jquery-3.6.0.min.js
      
    - name: Configurar variável de ambiente
      run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
      
    - name: Executar script
      run: node feed.js
