name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env: 
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: diretorio
        run: cd asouzaeletrica

      - name: Instalar dependências
        run: yarn

      - name: Executar testes
        run: yarn test --coverage --watchAll=false
