name: Exemplo de Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente
        run: echo "Configurando ambiente..."
      
      - name: Executar comando de exemplo
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          example-command "$API_TOKEN"
