name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Criar diretório para secrets.dart
        run: mkdir -p lib/path/to/
      - name: Decode base64 secrets and flutter pub get
        run: |
          echo $SECRETS_API_TOKEN | base64 -d > lib/path/to/secrets.dart
          export SECRETS_API_TOKEN=$SECRETS_API_TOKEN
          flutter pub get
        env:
          SECRETS_API_TOKEN: ${{ secrets.SECRETS_API_TOKEN }}
