name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set API Token
      run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

    - name: Substitute API Token in JavaScript
      run: sed -i "s/\${{ secrets.API_TOKEN }}/${{ secrets.API_TOKEN }}/g" feed.js

   
